source :rubygems

OS = Gem::Platform.local.os

gem "rake", ">= 0.9.2.2"
gem "jshint", ">= 0.1.1"
gem "sass", ">= 3.1.10"
gem "compass", ">= 0.11.5"
gem "fssm", ">= 0.2.7"
gem "closure-compiler", ">= 1.1.4"
gem "term-ansicolor", ">= 1.0.7"
gem "highline", "~> 1.6.8"

if OS == "darwin"
  gem "rb-fsevent", ">= 0.4.3.1"
  gem "json", ">= 1.6.1"
  gem "oily_png", ">= 1.0.2"
else
  gem "json_pure", ">= 1.6.3"
end
