source :rubygems

OS = Gem::Platform.local.os

gem "rake", ">= 0.9.2.2"
# gem "jshint", ">= 0.1.1"
gem "sass", ">= 3.1.12"
gem "compass", ">= 0.11.7"
gem "fssm", ">= 0.2.8.1"
gem "closure-compiler", ">= 1.1.5"
gem "term-ansicolor", ">= 1.0.7"
gem "highline", "~> 1.6.11"
gem "httpclient", ">= 2.2.4"
gem "smusher", ">= 0.4.9"
gem "uglifier", ">= 1.2.3"

if OS == "darwin"
  gem "rb-fsevent", ">= 0.9.0"
  gem "json", ">= 1.6.5"
  gem "oily_png", ">= 1.0.2"
else
  gem "json_pure", ">= 1.6.3"
end
